-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 22:56:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Localidad` (
  `Código Postal` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Código Postal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Teléfono` VARCHAR(45) NULL,
  `Localidad_Código Postal` INT NOT NULL,
  PRIMARY KEY (`DNI`, `Localidad_Código Postal`),
  INDEX `fk_Persona_Localidad1_idx` (`Localidad_Código Postal` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Localidad1`
    FOREIGN KEY (`Localidad_Código Postal`)
    REFERENCES `mydb`.`Localidad` (`Código Postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `nro_legajo` INT NULL,
  `E-mail` VARCHAR(45) NULL,
  `Edad` DATETIME NULL,
  `Persona_DNI` INT NOT NULL,
  `Localidad_Código Postal` INT NOT NULL,
  PRIMARY KEY (`nro_legajo`, `Persona_DNI`, `Localidad_Código Postal`),
  UNIQUE INDEX `nro_legajo_UNIQUE` (`nro_legajo` ASC) VISIBLE,
  INDEX `fk_Alumno_Persona1_idx` (`Persona_DNI` ASC) VISIBLE,
  INDEX `fk_Alumno_Localidad1_idx` (`Localidad_Código Postal` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_Persona1`
    FOREIGN KEY (`Persona_DNI`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Localidad1`
    FOREIGN KEY (`Localidad_Código Postal`)
    REFERENCES `mydb`.`Localidad` (`Código Postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesor` (
  `id_Profesor` INT NOT NULL,
  `Domicilio` VARCHAR(45) NULL,
  `Persona_DNI` INT NOT NULL,
  `Localidad_Código Postal` INT NOT NULL,
  PRIMARY KEY (`id_Profesor`, `Persona_DNI`, `Localidad_Código Postal`),
  INDEX `fk_Profesor_Persona1_idx` (`Persona_DNI` ASC) VISIBLE,
  INDEX `fk_Profesor_Localidad1_idx` (`Localidad_Código Postal` ASC) VISIBLE,
  CONSTRAINT `fk_Profesor_Persona1`
    FOREIGN KEY (`Persona_DNI`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_Localidad1`
    FOREIGN KEY (`Localidad_Código Postal`)
    REFERENCES `mydb`.`Localidad` (`Código Postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asignatura` (
  `id_Asignatura` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Carga horaria` INT NULL,
  `Profesor_id_Profesor` INT NOT NULL,
  `Profesor_Persona_DNI` INT NOT NULL,
  PRIMARY KEY (`id_Asignatura`, `Profesor_id_Profesor`, `Profesor_Persona_DNI`),
  INDEX `fk_Asignatura_Profesor1_idx` (`Profesor_id_Profesor` ASC, `Profesor_Persona_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Asignatura_Profesor1`
    FOREIGN KEY (`Profesor_id_Profesor` , `Profesor_Persona_DNI`)
    REFERENCES `mydb`.`Profesor` (`id_Profesor` , `Persona_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno_Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumno_Asignatura` (
  `Alumno_nro_legajo` INT NOT NULL,
  `Alumno_Persona_DNI` INT NOT NULL,
  `Asignatura_id_Asignatura` INT NOT NULL,
  `Horario` DATETIME NULL,
  `Nota` DECIMAL NULL,
  PRIMARY KEY (`Alumno_nro_legajo`, `Alumno_Persona_DNI`, `Asignatura_id_Asignatura`),
  INDEX `fk_Alumno_has_Asignatura_Asignatura1_idx` (`Asignatura_id_Asignatura` ASC) VISIBLE,
  INDEX `fk_Alumno_has_Asignatura_Alumno1_idx` (`Alumno_nro_legajo` ASC, `Alumno_Persona_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_has_Asignatura_Alumno1`
    FOREIGN KEY (`Alumno_nro_legajo` , `Alumno_Persona_DNI`)
    REFERENCES `mydb`.`Alumno` (`nro_legajo` , `Persona_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_Asignatura_Asignatura1`
    FOREIGN KEY (`Asignatura_id_Asignatura`)
    REFERENCES `mydb`.`Asignatura` (`id_Asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
